---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    reviewers:
      - "TomerFi"
    assignees:
      - "TomerFi"
    labels:
      - "dependabot"
    commit-message:
      prefix: "Python"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    reviewers:
      - "TomerFi"
    assignees:
      - "TomerFi"
    labels:
      - "dependabot"
    commit-message:
      prefix: "GHAction"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    reviewers:
      - "TomerFi"
    assignees:
      - "TomerFi"
    labels:
      - "dependabot"
    commit-message:
      prefix: "Docker"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "daily"
    target-branch: "dev"
    reviewers:
      - "TomerFi"
    assignees:
      - "TomerFi"
    labels:
      - "dependabot"
    commit-message:
      prefix: "Docker"
      include: "scope"
