# https://probot.github.io/apps/semantic-pull-requests/
---
# titleOnly: true
# titleAndCommits: true
commitsOnly: true
# anyCommit: true
# scopes:
#   - scope1
#   - scope2
types:
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert
allowMergeCommits: true
allowRevertCommits: true
