---
name: PullRequestsUtils

on: pull_request

jobs:
  triage:
    runs-on: ubuntu-latest
    name: Pull request triage
    steps:
      - name: Label pr based on content
        uses: actions/labeler@v2
        # fix for labeler bug not working for forks
        if: github.repository_owner == 'TomerFi'
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
