---
name: PreRelease

on:
  push:
    branches:
      - dev

jobs:
  pre-release:
    runs-on: ubuntu-latest
    name: Build pre-release and publish to GitHub
    steps:
      - name: Source checkout
        uses: actions/checkout@v2

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: latest

      - name: Get current date
        id: getDate
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.0.2
        with:
          driver-opts: image=moby/buildkit:buildx-stable-1

      - name: Login to GPR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.4.1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image and push to GPR
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v2
        with:
          tags: tomerfi/switcher_webapi:dev
          build-args: VCS_REF=$GITHUB_SHA,BUILD_DATE=${{ steps.getDate.outputs.date }},VERSION=dev
          push: true
